version: '2'

services:
  drupal:
    build: ./docker
    links:
    - mysql
    ports:
    - "0.0.0.0::80"
    volumes:
    #- ~/.composer/cache:/composer/cache
    - ./drupal:/var/www/html
    - ./config/settings.php:/var/www/html/sites/default/settings.php
    - ./install_profile/base:/var/www/html/profiles/base
    - ./docker/entrypoint:/docker-entrypoint.d
    - ./config/composer.json:/var/www/html/composer.json
    - ./config_import:/config
  mysql:
    image: mysql
    environment:
    - MYSQL_DATABASE=drupal
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
    - "0.0.0.0::3306"
